<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Employee.Domain\Employee.Domain.csproj" />
    <ProjectReference Include="..\Employee.Infrastructure\Employee.Infrastructure.csproj" />
  </ItemGroup>

</Project>
